services:
  doc-auto:
    build: .
    image: kirk/doc-auto:latest
    container_name: doc-auto
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - TZ=Asia/Shanghai
    working_dir: /app
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.address 0.0.0.0
    restart: unless-stopped
